baseURL = "https://techntalks.github.io/"
languageCode = "en-us"
title = "Tech Talks"
theme = 'my-theme'
paginate = 5

[params]
  author = "Tech Talks"
  description = "We are a friendly community with the only purpose of improving our English ❤️"
  cover = "/img/cover.png"
  twitter = "@lnxzpn"

[taxonomies]
  category = "categories"
  tag = "tags"
  kinds = 'kinds'

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/learning-resources"
    weight = 20
  [[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events"
    weight = 30

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "night-owl"
    tabWidth = 2